# Generated by Django 5.0.6 on 2025-11-06 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('type', models.CharField(choices=[('checking', 'Compte courant'), ('savings', 'Épargne'), ('broker', 'Courtier'), ('cash', 'Espèces'), ('credit', 'Crédit')], max_length=16)),
                ('interest_rate_apy', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='CashflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_description_regex', models.CharField(blank=True, max_length=255)),
                ('match_counterparty_regex', models.CharField(blank=True, max_length=255)),
                ('priority', models.IntegerField(default=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('instrument_type', models.CharField(default='stock', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('tax_wrapper', models.CharField(blank=True, max_length=8)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(default='yfinance', max_length=64)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('breakdown', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('is_transfer', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
            ],
            options={
                'indexes': [models.Index(fields=['posted_at'], name='finance_tra_posted__a1e407_idx'), models.Index(fields=['account', 'posted_at'], name='finance_tra_account_09b166_idx')],
            },
        ),
    ]
