# Generated by Django 5.0.6 on 2025-11-06 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='powens', max_length=32)),
                ('external_connection_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='created', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='finance.bankconnection')),
            ],
        ),
    ]
