# Generated by Django 5.0.6 on 2025-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bank_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconnection',
            name='access_token',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
