# Generated by Django 5.0.6 on 2025-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bank_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountlink',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
