# Generated by Django 5.0.6 on 2025-11-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_banklink_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_snapshot_date',
            field=models.DateField(blank=True, help_text='Date du snapshot du solde initial', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde initial avant toutes les transactions importées', max_digits=16),
        ),
    ]
