# Generated by Django 5.0.6 on 2025-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_account_balance_snapshot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solde brut du compte après cette transaction (depuis le CSV)', max_digits=16, null=True),
        ),
    ]
