# Generated by Django 5.0.6 on 2025-11-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_in_dashboard',
            field=models.BooleanField(default=True, help_text='Inclure ce compte dans les statistiques du dashboard'),
        ),
    ]
