# Generated by Django 4.2.26 on 2025-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portfolio_type',
            field=models.CharField(blank=True, choices=[('cto', 'Compte-Titres Ordinaire (CTO)'), ('pea', "Plan d'Épargne en Actions (PEA)"), ('pea_pme', 'PEA-PME'), ('crypto', 'Cryptomonnaies'), ('other', 'Autre')], help_text='Type de portefeuille pour les comptes courtier', max_length=16),
        ),
    ]
