# Generated by Django 4.2.26 on 2026-01-08 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0009_add_crypto_portfolio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], help_text='Type de synchronisation (manuelle ou automatique)', max_length=16)),
                ('status', models.CharField(choices=[('started', 'Démarrée'), ('success', 'Succès'), ('error', 'Erreur')], default='started', help_text='Statut de la synchronisation', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de début de la synchronisation')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date et heure de fin de la synchronisation', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec de la synchronisation")),
                ('transactions_count', models.IntegerField(default=0, help_text='Nombre de transactions synchronisées')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankconnection',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='external_connection_id',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bankconnection',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='account',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Activer la synchronisation automatique pour ce compte'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_connection',
            field=models.ForeignKey(blank=True, help_text='Connexion bancaire associée pour synchronisation automatique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='finance.bankconnection'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='account_name',
            field=models.CharField(default='', help_text='Nom du compte bancaire associé', max_length=120),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True, help_text='Activer la synchronisation automatique quotidienne'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='encrypted_credentials',
            field=models.TextField(default='', help_text='Credentials bancaires chiffrés avec AES-256'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière synchronisation réussie', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('syncing', 'Synchronisation en cours'), ('success', 'Succès'), ('error', 'Erreur')], default='pending', help_text='Statut actuel de la synchronisation', max_length=16),
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire de la connexion bancaire', on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='provider',
            field=models.CharField(choices=[('trade_republic', 'Trade Republic'), ('boursorama', 'BoursoBank'), ('hellobank', 'Hello Bank')], default='trade_republic', help_text='Provider bancaire (Trade Republic, BoursoBank, Hello Bank)', max_length=32),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['owner', 'provider'], name='finance_ban_owner_i_ba0a16_idx'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['sync_status'], name='finance_ban_sync_st_51429d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['last_sync_at'], name='finance_ban_last_sy_becb46_idx'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='bank_connection',
            field=models.ForeignKey(help_text='Connexion bancaire synchronisée', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='finance.bankconnection'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['bank_connection', '-started_at'], name='finance_syn_bank_co_915a08_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='finance_syn_status_3a9ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type'], name='finance_syn_sync_ty_004aeb_idx'),
        ),
    ]
