# Generated by Django 4.2.27 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_synclog_alter_bankconnection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='provider',
            field=models.CharField(choices=[('trade_republic', 'Trade Republic'), ('boursorama', 'BoursoBank'), ('hellobank', 'Hello Bank'), ('powens', 'Powens (API)')], default='trade_republic', help_text='Provider bancaire (Trade Republic, BoursoBank, Hello Bank)', max_length=32),
        ),
    ]
