# Generated by Django 4.2.30 on 2026-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_bankconnection_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
