# Generated by Django 4.2.30 on 2026-04-26 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_transaction_description_max_length_512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRepublicAccountValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(max_length=64)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('invested_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_societes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_crypto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_by_asset_type', models.JSONField(blank=True, default=dict)),
                ('societes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('crypto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('positions_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_with_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRepublicValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bridge_auto', 'Bridge automatique'), ('pdf_fallback', 'Import PDF fallback'), ('manual', 'Manuel'), ('legacy', 'Legacy')], default='bridge_auto', max_length=32)),
                ('auth_status', models.CharField(choices=[('authenticated', 'Authentifié'), ('needs_manual_auth', 'Authentification manuelle requise'), ('failed', 'Échec')], default='authenticated', max_length=32)),
                ('source_timestamp', models.DateTimeField()),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('invested_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_societes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_crypto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invested_by_asset_type', models.JSONField(blank=True, default=dict)),
                ('societes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('crypto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('positions_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_with_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bridge_latency_ms', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tr_valuation_snapshots', to='finance.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_valuation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeRepublicPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_type', models.CharField(choices=[('CTO', 'CTO'), ('PEA', 'PEA'), ('CRYPTO', 'CRYPTO'), ('PEA-PME', 'PEA-PME'), ('OTHER', 'Autre')], max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('invested_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('account_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='finance.traderepublicaccountvaluationsnapshot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='finance.traderepublicvaluationsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='traderepublicaccountvaluationsnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to='finance.traderepublicvaluationsnapshot'),
        ),
        migrations.AddIndex(
            model_name='traderepublicvaluationsnapshot',
            index=models.Index(fields=['owner', 'account', '-source_timestamp'], name='finance_tra_owner_i_1bdc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='traderepublicvaluationsnapshot',
            index=models.Index(fields=['source', '-source_timestamp'], name='finance_tra_source_0e7562_idx'),
        ),
        migrations.AddIndex(
            model_name='traderepublicportfoliosnapshot',
            index=models.Index(fields=['snapshot', 'portfolio_type'], name='finance_tra_snapsho_a9a507_idx'),
        ),
        migrations.AddIndex(
            model_name='traderepublicportfoliosnapshot',
            index=models.Index(fields=['portfolio_type', '-id'], name='finance_tra_portfol_49f5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='traderepublicaccountvaluationsnapshot',
            index=models.Index(fields=['snapshot', 'external_account_id'], name='finance_tra_snapsho_2894a4_idx'),
        ),
    ]
