# Generated by Django 4.2.30 on 2026-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_add_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(blank=True, choices=[('traderepublic', 'Trade Republic'), ('boursobank', 'BoursoBank'), ('hellobank_livret', 'Hello Bank (Livret)')], max_length=120),
        ),
    ]
