# Generated by Django 4.2.30 on 2026-06-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0015_account_provider_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRepublicSubAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(help_text='Numéro de compte-titres Trade Republic (secAccNo)', max_length=64)),
                ('portfolio_type', models.CharField(blank=True, choices=[('CTO', 'CTO'), ('PEA', 'PEA'), ('CRYPTO', 'CRYPTO'), ('PEA-PME', 'PEA-PME'), ('OTHER', 'Autre')], help_text='Type de portefeuille fiscal (vide = à classer)', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_subaccount_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'external_account_id')},
            },
        ),
    ]
